-- 5.1 회원 테이블
CREATE TABLE USER_INFO (
    USR_ID VARCHAR2(50) PRIMARY KEY,
    USR_PWD VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    AUTH_CD VARCHAR2(10),
    REGIST_DE DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN USER_INFO.USR_ID IS 'PK / 아이디';
COMMENT ON COLUMN USER_INFO.USR_PWD IS 'SHA-256 암호화';
COMMENT ON COLUMN USER_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN USER_INFO.AUTH_CD IS '권한 코드(AUTH001 관리자, AUTH002 일반사용자)';
COMMENT ON COLUMN USER_INFO.REGIST_DE IS '등록일';

-- 5.2 일정 테이블
CREATE TABLE SCHEDULE (
    SCHEDULE_SN NUMBER(10) PRIMARY KEY,
    SCHEDULE_NM VARCHAR2(100) NOT NULL,
    SCHEDULE_CN VARCHAR2(2000),
    SCHEDULE_START_DE DATE NOT NULL,
    SCHEDULE_END_DE DATE NOT NULL,
    SCHEDULE_FILE_PATH VARCHAR2(200),
    SCHEDULE_FILE_NM VARCHAR2(200),
    SCHEDULE_FILE_ORG_NM VARCHAR2(200),
    REGIST_DE DATE DEFAULT SYSDATE,
    REGIST_ID VARCHAR2(50),
    UPDATE_DE DATE,
    UPDATE_ID VARCHAR2(50),
    SCHEDULE_ADRES VARCHAR2(500)
);

COMMENT ON COLUMN SCHEDULE.SCHEDULE_SN IS 'PK';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_NM IS '일정명';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_CN IS '일정내용';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_START_DE IS '시작일';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_END_DE IS '종료일';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_FILE_PATH IS '파일 경로';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_FILE_NM IS '서버 저장 파일명';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_FILE_ORG_NM IS '원본 파일명';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_REGIST_DE IS '등록일';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_REGIST_ID IS '등록자';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_UPDATE_DE IS '수정일';
COMMENT ON COLUMN SCHEDULE.SCHEDULE_UPDATE_ID IS '수정자';

-- Sequence
CREATE SEQUENCE SEQ_SCHEDULE_SN
START WITH 1
INCREMENT BY 1
NOCACHE;

-- Initial data for test (Optional)
INSERT INTO USER_INFO (USR_ID, USR_PWD, EMAIL, AUTH_CD, REGIST_DE) 
VALUES ('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 'admin@test.com', 'AUTH001', SYSDATE);
-- Password above is SHA-256 for 'admin'
